package generator

import (
	"bytes"
	"text/template"

	"github.com/chinmayrelkar/bawarchi/internal/parser"
)

// Generated gRPC CLIs shell out to grpcurl, which handles proto encoding/decoding.
// Requires grpcurl to be installed: https://github.com/fullstorydev/grpcurl
const grpcTemplate = `// Code generated by bawarchi. DO NOT EDIT.
// Requires grpcurl: https://github.com/fullstorydev/grpcurl
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
)

const (
	serverAddr = "{{.BaseURL}}"
	authEnvVar = "{{.AuthEnvVar}}"
)

func main() {
	if len(os.Args) < 2 || os.Args[1] == "--help" || os.Args[1] == "-h" || os.Args[1] == "help" {
		printUsage()
		os.Exit(0)
	}
	switch os.Args[1] {
{{- range .Commands}}
	case "{{.Name}}":
		cmd{{.GoName}}(os.Args[2:])
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n", os.Args[1])
		fmt.Fprintln(os.Stderr, "Run with --help for usage.")
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println("{{.Name}} — {{safeStr .Description}}")
	fmt.Println()
	fmt.Println("Usage: {{.Name}} <command> [flags]")
	fmt.Println()
	fmt.Println("Commands:")
{{- range .Commands}}
	fmt.Printf("  %-20s %s\n", "{{.Name}}", "{{safeStr .Description}}")
{{- end}}
	fmt.Printf("\nServer: %s\n", serverAddr)
	fmt.Printf("Auth:   set %s env var for bearer token (required)\n", authEnvVar)
	fmt.Println("Hint:   use // @service: <fully.qualified.ServicePath> in your .proto to set the gRPC service prefix")
}

func grpcCall(service, method string, fields map[string]string) {
	// Build JSON body from fields
	bodyBytes, err := json.Marshal(fields)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: failed to marshal request body: %v\n", err)
		os.Exit(1)
	}
	body := string(bodyBytes)

	args := []string{"-plaintext"}

	// Auth
	key := os.Getenv(authEnvVar)
	if key == "" {
		fmt.Fprintf(os.Stderr, "error: required env var %s is not set\n", authEnvVar)
		os.Exit(1)
	}
	args = append(args, "-H", "Authorization: Bearer "+key)

	args = append(args, "-d", body, serverAddr, service+"/"+method)

	cmd := exec.Command("grpcurl", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		os.Exit(1)
	}
}
{{range .Commands}}
{{- $cmd := .}}
// {{.Name}}: {{.Description}}
func cmd{{.GoName}}(args []string) {
{{- if gt (len .Operations) 1}}
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		fmt.Println("Usage: {{$.Name}} {{.Name}} <subcommand> [flags]")
		fmt.Println()
		fmt.Println("Subcommands:")
{{- range .Operations}}
		fmt.Printf("  %-20s %s\n", "{{.Name}}", "{{safeStr .Description}}")
{{- end}}
		return
	}
	switch args[0] {
{{- range .Operations}}
	case "{{.Name}}":
		op{{$cmd.GoName}}{{.GoName}}(args[1:])
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand: %s\n", args[0])
		os.Exit(1)
	}
{{- else}}{{with index .Operations 0}}
	op{{$cmd.GoName}}{{.GoName}}(args)
{{- end}}{{end}}
}
{{range .Operations}}
func op{{$cmd.GoName}}{{.GoName}}(args []string) {
	fs := flag.NewFlagSet("{{$.Name}} {{$cmd.Name}} {{.Name}}", flag.ExitOnError)
{{- range .InputParams}}
	var p{{.GoVarName}} {{.GoType}} = {{.DefaultLiteral}}
	fs.{{.FlagFunc}}(&p{{.GoVarName}}, "{{.FlagName}}", {{.DefaultLiteral}}, "{{safeStr .Description}}")
{{- end}}
	fs.Parse(args)

	fields := map[string]string{}
{{- range .InputParams}}
	if p{{.GoVarName}} {{.DefaultCmp}} {
		fields["{{.Name}}"] = fmt.Sprintf("%v", p{{.GoVarName}})
	}
{{- end}}
	grpcCall("{{.GRPCService}}", "{{.GRPCMethod}}", fields)
}
{{end}}{{end}}`

func generateGRPC(data *parser.CLIData) ([]byte, error) {
	tmpl, err := template.New("grpc").Funcs(tmplFuncs).Parse(grpcTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
