package generator

import (
	"bytes"
	"text/template"

	"github.com/chinmayrelkar/bawarchi/internal/parser"
)

const restTemplate = `// Code generated by bawarchi. DO NOT EDIT.
package main

import (
{{if .HasBodyParams}}	"bytes"
{{end}}	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
{{if or .HasArrayParams (gt (len .Servers) 1)}}	"strconv"
{{end}}	"strings"
	"time"{{if .AuthImport}}
	{{.AuthImport}}{{end}}
)

const authEnvVar = "{{.AuthEnvVar}}"

var (
	baseURL    = "{{.BaseURL}}"
	httpClient = &http.Client{Timeout: 30 * time.Second}
)

func init() {
{{- if gt (len .Servers) 1}}
	servers := []string{
{{- range .Servers}}
		"{{.URL}}",
{{- end}}
	}
	if v := os.Getenv("{{.ServerEnvVar}}"); v != "" {
		if idx, err := strconv.Atoi(v); err == nil && idx >= 0 && idx < len(servers) {
			baseURL = servers[idx]
		} else {
			fmt.Fprintf(os.Stderr, "warning: %s=%q is not a valid server index (0..%d); using default\n", "{{.ServerEnvVar}}", v, len(servers)-1)
		}
	}
{{- end}}
	if v := os.Getenv("{{.BaseURLEnvVar}}"); v != "" {
		baseURL = strings.TrimRight(v, "/")
	}
}

func main() {
	if len(os.Args) < 2 || os.Args[1] == "--help" || os.Args[1] == "-h" || os.Args[1] == "help" {
		printUsage()
		os.Exit(0)
	}
	switch os.Args[1] {
{{- range .Commands}}
	case "{{.Name}}":
		cmd{{.GoName}}(os.Args[2:])
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n", os.Args[1])
		fmt.Fprintln(os.Stderr, "Run with --help for usage.")
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println("{{.Name}} — {{safeStr .Description}}")
	fmt.Println()
	fmt.Println("Usage: {{.Name}} <command> [flags]")
	fmt.Println()
	fmt.Println("Commands:")
{{- range .Commands}}
	fmt.Printf("  %-20s %s\n", "{{.Name}}", "{{safeStr .Description}}")
{{- end}}
	fmt.Printf("\nAuth:    set %s{{if .AuthImport}} (format: email:apikey){{end}}\n", authEnvVar)
	fmt.Printf("Base URL: %s (override with %s)\n", baseURL, "{{.BaseURLEnvVar}}")
{{- if gt (len .Servers) 1}}
	fmt.Println("Servers (select with {{.ServerEnvVar}}=<index>):")
{{- range $i, $s := .Servers}}
	fmt.Printf("  [%d] %s{{if $s.Description}} — {{safeStr $s.Description}}{{end}}\n", {{$i}}, "{{$s.URL}}")
{{- end}}
{{- end}}
}

func doRequest(method, rawURL string, body io.Reader, headers map[string]string) {
	key := os.Getenv(authEnvVar)
	if key == "" {
		fmt.Fprintf(os.Stderr, "error: %s not set\n", authEnvVar)
		os.Exit(1)
	}
	req, err := http.NewRequest(method, rawURL, body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	{{.AuthSetup}}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := httpClient.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()
	var data []byte
	data, err = io.ReadAll(resp.Body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading response: %v\n", err)
		os.Exit(1)
	}
	var out interface{}
	if json.Unmarshal(data, &out) == nil {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		enc.Encode(out)
	} else {
		os.Stdout.Write(data)
	}
	// Standardized exit codes: 0 success, 4 client error (4xx), 5 server error (5xx).
	if resp.StatusCode >= 500 {
		os.Exit(5)
	}
	if resp.StatusCode >= 400 {
		os.Exit(4)
	}
}
{{range .Commands}}
{{- $cmd := .}}
// {{.Name}}: {{.Description}}
func cmd{{.GoName}}(args []string) {
{{- if gt (len .Operations) 1}}
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		fmt.Println("Usage: {{$.Name}} {{.Name}} <subcommand> [flags]")
		fmt.Println()
		fmt.Println("Subcommands:")
{{- range .Operations}}
		fmt.Printf("  %-20s %s\n", "{{.Name}}", "{{safeStr .Description}}")
{{- end}}
		return
	}
	switch args[0] {
{{- range .Operations}}
	case "{{.Name}}":
		op{{$cmd.GoName}}{{.GoName}}(args[1:])
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand: %s\n", args[0])
		os.Exit(1)
	}
{{- else}}{{with index .Operations 0}}
	op{{$cmd.GoName}}{{.GoName}}(args)
{{- end}}{{end}}
}
{{range .Operations}}
func op{{$cmd.GoName}}{{.GoName}}(args []string) {
	fs := flag.NewFlagSet("{{$.Name}} {{$cmd.Name}} {{.Name}}", flag.ExitOnError)
{{- range .QueryParams}}
	var p{{.GoVarName}} {{.GoType}} = {{.DefaultLiteral}}
	fs.{{.FlagFunc}}(&p{{.GoVarName}}, "{{.FlagName}}", {{.DefaultLiteral}}, "{{safeStr .Description}}{{if .Required}} (required){{end}}")
{{- end}}
{{- range .PathParams}}
	var p{{.GoVarName}} string
	fs.StringVar(&p{{.GoVarName}}, "{{.FlagName}}", "", "{{safeStr .Description}} (required)")
{{- end}}
{{- range .BodyParams}}
	var p{{.GoVarName}} {{.GoType}} = {{.DefaultLiteral}}
	fs.{{.FlagFunc}}(&p{{.GoVarName}}, "{{.FlagName}}", {{.DefaultLiteral}}, "{{safeStr .Description}}{{if .Required}} (required){{end}}")
{{- end}}
{{- range .HeaderParams}}
	var p{{.GoVarName}} string
	fs.StringVar(&p{{.GoVarName}}, "{{.FlagName}}", "", "{{safeStr .Description}} (HTTP header){{if .Required}} (required){{end}}")
{{- end}}
	fs.Parse(args)
{{range .PathParams}}
	if p{{.GoVarName}} == "" {
		fmt.Fprintf(os.Stderr, "error: --{{.FlagName}} is required\n")
		os.Exit(1)
	}
{{- end}}
{{- range .QueryParams}}
{{- if and .Required (ne .GoType "bool")}}
	if p{{.GoVarName}} {{.ZeroCmp}} {
		fmt.Fprintf(os.Stderr, "error: --{{.FlagName}} is required\n")
		os.Exit(1)
	}
{{- end}}
{{- end}}
{{- range .HeaderParams}}
{{- if .Required}}
	if p{{.GoVarName}} == "" {
		fmt.Fprintf(os.Stderr, "error: --{{.FlagName}} is required\n")
		os.Exit(1)
	}
{{- end}}
{{- end}}
{{- range .BodyParams}}
{{- if and .Required (ne .GoType "bool")}}
	if p{{.GoVarName}} {{.ZeroCmp}} {
		fmt.Fprintf(os.Stderr, "error: --{{.FlagName}} is required\n")
		os.Exit(1)
	}
{{- end}}
{{- end}}
	path := "{{.Path}}"
{{- range .PathParams}}
	path = strings.ReplaceAll(path, "{{.PathPlaceholder}}", p{{.GoVarName}})
{{- end}}
	u, err := url.Parse(baseURL + path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error building URL: %v\n", err)
		os.Exit(1)
	}
	q := u.Query()
{{- range .QueryParams}}
{{- if .IsArray}}
	if p{{.GoVarName}} != "" {
		for _, v := range splitList(p{{.GoVarName}}) {
			q.Add("{{.Name}}", v)
		}
	}
{{- else}}
	if p{{.GoVarName}} {{.DefaultCmp}} {
		q.Set("{{.Name}}", fmt.Sprintf("%v", p{{.GoVarName}}))
	}
{{- end}}
{{- end}}
	u.RawQuery = q.Encode()
{{- if .HeaderParams}}
	hdrs := map[string]string{}
{{- range .HeaderParams}}
	if p{{.GoVarName}} != "" {
		hdrs["{{.Name}}"] = p{{.GoVarName}}
	}
{{- end}}
{{- end}}
{{- if .BodyParams}}
	reqBody := map[string]interface{}{}
{{- range .BodyParams}}
{{- if .IsArray}}
	if p{{.GoVarName}} != "" {
		reqBody["{{.Name}}"] = {{listConv .ElemType}}(p{{.GoVarName}})
	}
{{- else}}
	if p{{.GoVarName}} {{.DefaultCmp}} {
		reqBody["{{.Name}}"] = p{{.GoVarName}}
	}
{{- end}}
{{- end}}
	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error building request body: %v\n", err)
		os.Exit(1)
	}
	doRequest("{{.Method}}", u.String(), bytes.NewReader(bodyBytes), {{if .HeaderParams}}hdrs{{else}}nil{{end}})
{{- else}}
	doRequest("{{.Method}}", u.String(), nil, {{if .HeaderParams}}hdrs{{else}}nil{{end}})
{{- end}}
}
{{end}}{{end}}
{{- if .HasArrayParams}}
// splitList parses a comma-separated flag value into trimmed, non-empty items.
func splitList(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func toIntList(s string) []int {
	var out []int
	for _, p := range splitList(s) {
		n, err := strconv.Atoi(p)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %q is not an integer\n", p)
			os.Exit(1)
		}
		out = append(out, n)
	}
	return out
}

func toFloatList(s string) []float64 {
	var out []float64
	for _, p := range splitList(s) {
		f, err := strconv.ParseFloat(p, 64)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %q is not a number\n", p)
			os.Exit(1)
		}
		out = append(out, f)
	}
	return out
}

func toBoolList(s string) []bool {
	var out []bool
	for _, p := range splitList(s) {
		b, err := strconv.ParseBool(p)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %q is not a boolean\n", p)
			os.Exit(1)
		}
		out = append(out, b)
	}
	return out
}
{{- end}}`

func generateREST(data *parser.CLIData) ([]byte, error) {
	tmpl, err := template.New("rest").Funcs(tmplFuncs).Parse(restTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
