package generator

import (
	"bytes"
	"text/template"

	"github.com/chinmayrelkar/bawarchi/internal/parser"
)

const restTemplate = `// Code generated by bawarchi. DO NOT EDIT.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"{{if .HasPathParams}}
	"strings"{{end}}
)

const (
	baseURL    = "{{.BaseURL}}"
	authEnvVar = "{{.AuthEnvVar}}"
)

func main() {
	if len(os.Args) < 2 || os.Args[1] == "--help" || os.Args[1] == "-h" || os.Args[1] == "help" {
		printUsage()
		os.Exit(0)
	}
	switch os.Args[1] {
{{- range .Commands}}
	case "{{.Name}}":
		cmd{{.GoName}}(os.Args[2:])
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n", os.Args[1])
		fmt.Fprintln(os.Stderr, "Run with --help for usage.")
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println("{{.Name}} — {{safeStr .Description}}")
	fmt.Println()
	fmt.Println("Usage: {{.Name}} <command> [flags]")
	fmt.Println()
	fmt.Println("Commands:")
{{- range .Commands}}
	fmt.Printf("  %-20s %s\n", "{{.Name}}", "{{safeStr .Description}}")
{{- end}}
	fmt.Printf("\nRequires %s environment variable.\n", authEnvVar)
}

func doRequest(method, rawURL string, body io.Reader) {
	key := os.Getenv(authEnvVar)
	if key == "" {
		fmt.Fprintf(os.Stderr, "error: %s not set\n", authEnvVar)
		os.Exit(1)
	}
	req, err := http.NewRequest(method, rawURL, body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	{{.AuthSetup}}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(resp.Body)
	var out interface{}
	if json.Unmarshal(data, &out) == nil {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		enc.Encode(out)
	} else {
		os.Stdout.Write(data)
	}
	if resp.StatusCode >= 400 {
		os.Exit(1)
	}
}
{{range .Commands}}
{{- $cmd := .}}
// {{.Name}}: {{.Description}}
func cmd{{.GoName}}(args []string) {
{{- if gt (len .Operations) 1}}
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		fmt.Println("Usage: {{$.Name}} {{.Name}} <subcommand> [flags]")
		fmt.Println()
		fmt.Println("Subcommands:")
{{- range .Operations}}
		fmt.Printf("  %-20s %s\n", "{{.Name}}", "{{safeStr .Description}}")
{{- end}}
		return
	}
	switch args[0] {
{{- range .Operations}}
	case "{{.Name}}":
		op{{$cmd.GoName}}{{.GoName}}(args[1:])
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand: %s\n", args[0])
		os.Exit(1)
	}
{{- else}}{{with index .Operations 0}}
	op{{$cmd.GoName}}{{.GoName}}(args)
{{- end}}{{end}}
}
{{range .Operations}}
func op{{$cmd.GoName}}{{.GoName}}(args []string) {
	fs := flag.NewFlagSet("{{$.Name}} {{$cmd.Name}} {{.Name}}", flag.ExitOnError)
{{- range .QueryParams}}
	var p{{.GoVarName}} {{.GoType}} = {{.DefaultLiteral}}
	fs.{{.FlagFunc}}(&p{{.GoVarName}}, "{{.FlagName}}", {{.DefaultLiteral}}, "{{safeStr .Description}}")
{{- end}}
{{- range .PathParams}}
	var p{{.GoVarName}} string
	fs.StringVar(&p{{.GoVarName}}, "{{.FlagName}}", "", "{{safeStr .Description}} (required)")
{{- end}}
	fs.Parse(args)
{{range .PathParams}}
	if p{{.GoVarName}} == "" {
		fmt.Fprintf(os.Stderr, "error: --{{.FlagName}} is required\n")
		os.Exit(1)
	}
{{- end}}
	path := "{{.Path}}"
{{- range .PathParams}}
	path = strings.ReplaceAll(path, "{{.PathPlaceholder}}", p{{.GoVarName}})
{{- end}}
	u, err := url.Parse(baseURL + path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error building URL: %v\n", err)
		os.Exit(1)
	}
	q := u.Query()
{{- range .QueryParams}}
	if p{{.GoVarName}} {{.DefaultCmp}} {
		q.Set("{{.Name}}", fmt.Sprintf("%v", p{{.GoVarName}}))
	}
{{- end}}
	u.RawQuery = q.Encode()
	doRequest("{{.Method}}", u.String(), nil)
}
{{end}}{{end}}`

func generateREST(data *parser.CLIData) ([]byte, error) {
	tmpl, err := template.New("rest").Funcs(tmplFuncs).Parse(restTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
